general.import = ["/Users/alessandrodominici/.config/alacritty/themes/themes/tokyo-night.toml"]
general.live_config_reload = true

[font]
size = 18

# [font.bold]
# family = "VictorMono Nerd Font"
# style = "Medium"
#
# [font.italic]
# family = "VictorMono Nerd Font"
# style = "Light Italic"

[font.normal]
family = "VictorMono Nerd Font"
style = "SemiBold"

[scrolling]
history = 10000
multiplier = 3

[window]
option_as_alt = "Both"
decorations = "Full"
decorations_theme_variant = "dark"
opacity = 0.95
blur = true
# startup_mode = "SimpleFullscreen"

[window.padding]
x = 0
y = 0
